### ISSUE TITLE
Is it still under maintained?

### ISSUE THREAD

**Issue by jasonjoo2010** [angopher/chronus#13]
We are interested on it and plan to apply it in production after more testing.

请问还在维护吗？
我们很感兴趣influxdb的开源集群方案，很高兴找到chronus。

**Comment by angopher** [comment]
由于工作原因，暂时没有精力投入在这个项目中，目前这个项目可以作为InfluxDB集群方案的一个参考，不建议生产环境使用

**Comment by jasonjoo2010** [comment]
> 由于工作原因，暂时没有精力投入在这个项目中，目前这个项目可以作为InfluxDB集群方案的一个参考，不建议生产环境使用

感谢回应

那么目前的状态是做了部分实现，or实现完成，or做了一定规模的使用？
因为本来我们也是在寻找or开发基于relay/cluster方向的方案

**Comment by angopher** [comment]
功能层面实现得算是比较完善了，如果有兴趣进一步交流时序数据库方面的技术，可以扫描README下方的二维码加微信聊
